{
 "title": "KilluaDB API Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(killuadb_api_requests_total, method)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(killuadb_api_requests_total, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Shows the percentiles of request latency for a specific endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(killuadb_api_request_duration_seconds_bucket{method=~\"$method\",path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(killuadb_api_request_duration_seconds_bucket{method=~\"$method\",path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(killuadb_api_request_duration_seconds_bucket{method=~\"$method\",path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(killuadb_api_request_duration_seconds_bucket{method=~\"$method\",path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Error rate percentage",
   "type": "timeseries",
   "description": "Shows the error rate percentage of a specific endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(killuadb_api_requests_total{method=~\"$method\",path=~\"$path\",status=~\"5..|4..\"}[5m])) / sum(rate(killuadb_api_requests_total{method=~\"$method\",path=~\"$path\"}[5m])))",
     "legendFormat": "Error rate percentage"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Shows the throughput of a specific endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(killuadb_api_requests_total{method=~\"$method\",path=~\"$path\"}[1m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Trend of error codes",
   "type": "timeseries",
   "description": "Shows the trend that different error codes are taking",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(status)(rate(killuadb_api_requests_total{method=~\"$method\",path=~\"$path\",status=~\"5..|4..\"}[5m])) / ignoring(status) group_left sum(rate(killuadb_api_requests_total{method=~\"$method\",path=~\"$path\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}