apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  PORT: "8080"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "dbaas"
  REDIS_ADDR: "redis:6379"
  DB_USERNAME: "postgres"
  DB_INSTANCES_NAMESPACE_POSTGRES: "postgres-instances"
  DB_INSTANCES_NAMESPACE_MONGO: "mongodb-instances"
  GOOGLE_REDIRECT_URL: "http://localhost:8080/api/v1/auth/google/callback"
  TEXT_TO_SQL: "http://text-to-sql.default.svc.cluster.local:8080"
  SCHEMA_AI_BASE_URL: "http://ai-service.default.svc.cluster.local:8080"
  EXTERNAL_DB_DOMAIN: "127.0.0.1.nip.io"