apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: meta-db
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: dbaas
      owner: dbaas

  storage:
    size: 10Gi
    storageClass: local-path     

